/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as LoginImport } from "./routes/login";
import { Route as AuthImport } from "./routes/_auth";
import { Route as IndexImport } from "./routes/index";
import { Route as AuthSettingsImport } from "./routes/_auth.settings";
import { Route as AuthAchievementsImport } from "./routes/_auth.achievements";
import { Route as AuthSettingsUserImport } from "./routes/_auth.settings.user";
import { Route as AuthSettingsAchievementsImport } from "./routes/_auth.settings.achievements";
import { Route as AuthAchievementsIdImport } from "./routes/_auth.achievements_.$id";
import { Route as AuthSettingsAchievementsCreateImport } from "./routes/_auth.settings.achievements_.create";
import { Route as AuthSettingsAchievementsIdImport } from "./routes/_auth.settings.achievements_.$id";

// Create/Update Routes

const LoginRoute = LoginImport.update({
	path: "/login",
	getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
	id: "/_auth",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

const AuthSettingsRoute = AuthSettingsImport.update({
	path: "/settings",
	getParentRoute: () => AuthRoute,
} as any);

const AuthAchievementsRoute = AuthAchievementsImport.update({
	path: "/achievements",
	getParentRoute: () => AuthRoute,
} as any);

const AuthSettingsUserRoute = AuthSettingsUserImport.update({
	path: "/user",
	getParentRoute: () => AuthSettingsRoute,
} as any);

const AuthSettingsAchievementsRoute = AuthSettingsAchievementsImport.update({
	path: "/achievements",
	getParentRoute: () => AuthSettingsRoute,
} as any);

const AuthAchievementsIdRoute = AuthAchievementsIdImport.update({
	path: "/achievements/$id",
	getParentRoute: () => AuthRoute,
} as any);

const AuthSettingsAchievementsCreateRoute =
	AuthSettingsAchievementsCreateImport.update({
		path: "/achievements/create",
		getParentRoute: () => AuthSettingsRoute,
	} as any);

const AuthSettingsAchievementsIdRoute = AuthSettingsAchievementsIdImport.update(
	{
		path: "/achievements/$id",
		getParentRoute: () => AuthSettingsRoute,
	} as any,
);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/_auth": {
			id: "/_auth";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthImport;
			parentRoute: typeof rootRoute;
		};
		"/login": {
			id: "/login";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginImport;
			parentRoute: typeof rootRoute;
		};
		"/_auth/achievements": {
			id: "/_auth/achievements";
			path: "/achievements";
			fullPath: "/achievements";
			preLoaderRoute: typeof AuthAchievementsImport;
			parentRoute: typeof AuthImport;
		};
		"/_auth/settings": {
			id: "/_auth/settings";
			path: "/settings";
			fullPath: "/settings";
			preLoaderRoute: typeof AuthSettingsImport;
			parentRoute: typeof AuthImport;
		};
		"/_auth/achievements/$id": {
			id: "/_auth/achievements/$id";
			path: "/achievements/$id";
			fullPath: "/achievements/$id";
			preLoaderRoute: typeof AuthAchievementsIdImport;
			parentRoute: typeof AuthImport;
		};
		"/_auth/settings/achievements": {
			id: "/_auth/settings/achievements";
			path: "/achievements";
			fullPath: "/settings/achievements";
			preLoaderRoute: typeof AuthSettingsAchievementsImport;
			parentRoute: typeof AuthSettingsImport;
		};
		"/_auth/settings/user": {
			id: "/_auth/settings/user";
			path: "/user";
			fullPath: "/settings/user";
			preLoaderRoute: typeof AuthSettingsUserImport;
			parentRoute: typeof AuthSettingsImport;
		};
		"/_auth/settings/achievements/$id": {
			id: "/_auth/settings/achievements/$id";
			path: "/achievements/$id";
			fullPath: "/settings/achievements/$id";
			preLoaderRoute: typeof AuthSettingsAchievementsIdImport;
			parentRoute: typeof AuthSettingsImport;
		};
		"/_auth/settings/achievements/create": {
			id: "/_auth/settings/achievements/create";
			path: "/achievements/create";
			fullPath: "/settings/achievements/create";
			preLoaderRoute: typeof AuthSettingsAchievementsCreateImport;
			parentRoute: typeof AuthSettingsImport;
		};
	}
}

// Create and export the route tree

interface AuthSettingsRouteChildren {
	AuthSettingsAchievementsRoute: typeof AuthSettingsAchievementsRoute;
	AuthSettingsUserRoute: typeof AuthSettingsUserRoute;
	AuthSettingsAchievementsIdRoute: typeof AuthSettingsAchievementsIdRoute;
	AuthSettingsAchievementsCreateRoute: typeof AuthSettingsAchievementsCreateRoute;
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
	AuthSettingsAchievementsRoute: AuthSettingsAchievementsRoute,
	AuthSettingsUserRoute: AuthSettingsUserRoute,
	AuthSettingsAchievementsIdRoute: AuthSettingsAchievementsIdRoute,
	AuthSettingsAchievementsCreateRoute: AuthSettingsAchievementsCreateRoute,
};

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
	AuthSettingsRouteChildren,
);

interface AuthRouteChildren {
	AuthAchievementsRoute: typeof AuthAchievementsRoute;
	AuthSettingsRoute: typeof AuthSettingsRouteWithChildren;
	AuthAchievementsIdRoute: typeof AuthAchievementsIdRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
	AuthAchievementsRoute: AuthAchievementsRoute,
	AuthSettingsRoute: AuthSettingsRouteWithChildren,
	AuthAchievementsIdRoute: AuthAchievementsIdRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"": typeof AuthRouteWithChildren;
	"/login": typeof LoginRoute;
	"/achievements": typeof AuthAchievementsRoute;
	"/settings": typeof AuthSettingsRouteWithChildren;
	"/achievements/$id": typeof AuthAchievementsIdRoute;
	"/settings/achievements": typeof AuthSettingsAchievementsRoute;
	"/settings/user": typeof AuthSettingsUserRoute;
	"/settings/achievements/$id": typeof AuthSettingsAchievementsIdRoute;
	"/settings/achievements/create": typeof AuthSettingsAchievementsCreateRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"": typeof AuthRouteWithChildren;
	"/login": typeof LoginRoute;
	"/achievements": typeof AuthAchievementsRoute;
	"/settings": typeof AuthSettingsRouteWithChildren;
	"/achievements/$id": typeof AuthAchievementsIdRoute;
	"/settings/achievements": typeof AuthSettingsAchievementsRoute;
	"/settings/user": typeof AuthSettingsUserRoute;
	"/settings/achievements/$id": typeof AuthSettingsAchievementsIdRoute;
	"/settings/achievements/create": typeof AuthSettingsAchievementsCreateRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRoute;
	"/_auth": typeof AuthRouteWithChildren;
	"/login": typeof LoginRoute;
	"/_auth/achievements": typeof AuthAchievementsRoute;
	"/_auth/settings": typeof AuthSettingsRouteWithChildren;
	"/_auth/achievements/$id": typeof AuthAchievementsIdRoute;
	"/_auth/settings/achievements": typeof AuthSettingsAchievementsRoute;
	"/_auth/settings/user": typeof AuthSettingsUserRoute;
	"/_auth/settings/achievements/$id": typeof AuthSettingsAchievementsIdRoute;
	"/_auth/settings/achievements/create": typeof AuthSettingsAchievementsCreateRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths:
		| "/"
		| ""
		| "/login"
		| "/achievements"
		| "/settings"
		| "/achievements/$id"
		| "/settings/achievements"
		| "/settings/user"
		| "/settings/achievements/$id"
		| "/settings/achievements/create";
	fileRoutesByTo: FileRoutesByTo;
	to:
		| "/"
		| ""
		| "/login"
		| "/achievements"
		| "/settings"
		| "/achievements/$id"
		| "/settings/achievements"
		| "/settings/user"
		| "/settings/achievements/$id"
		| "/settings/achievements/create";
	id:
		| "__root__"
		| "/"
		| "/_auth"
		| "/login"
		| "/_auth/achievements"
		| "/_auth/settings"
		| "/_auth/achievements/$id"
		| "/_auth/settings/achievements"
		| "/_auth/settings/user"
		| "/_auth/settings/achievements/$id"
		| "/_auth/settings/achievements/create";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	AuthRoute: typeof AuthRouteWithChildren;
	LoginRoute: typeof LoginRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	AuthRoute: AuthRouteWithChildren,
	LoginRoute: LoginRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/achievements",
        "/_auth/settings",
        "/_auth/achievements/$id"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/achievements": {
      "filePath": "_auth.achievements.tsx",
      "parent": "/_auth"
    },
    "/_auth/settings": {
      "filePath": "_auth.settings.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/settings/achievements",
        "/_auth/settings/user",
        "/_auth/settings/achievements/$id",
        "/_auth/settings/achievements/create"
      ]
    },
    "/_auth/achievements/$id": {
      "filePath": "_auth.achievements_.$id.tsx",
      "parent": "/_auth"
    },
    "/_auth/settings/achievements": {
      "filePath": "_auth.settings.achievements.tsx",
      "parent": "/_auth/settings"
    },
    "/_auth/settings/user": {
      "filePath": "_auth.settings.user.tsx",
      "parent": "/_auth/settings"
    },
    "/_auth/settings/achievements/$id": {
      "filePath": "_auth.settings.achievements_.$id.tsx",
      "parent": "/_auth/settings"
    },
    "/_auth/settings/achievements/create": {
      "filePath": "_auth.settings.achievements_.create.tsx",
      "parent": "/_auth/settings"
    }
  }
}
ROUTE_MANIFEST_END */
